# URL de conexão: o "endereço" do seu banco no seu próprio PC (localhost)
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db

# As credenciais que você definiu na instalação
spring.datasource.username=postgres
spring.datasource.password=1018

# Driver que faz a ponte entre Java e Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Comando para o Hibernate (Spring Data) criar as tabelas automaticamente para você
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos que o Spring está enviando para o banco (ótimo para aprender)
spring.jpa.show-sql=true
server.port=8081